kind: Service
apiVersion: v1
metadata:
  name: jade-accounts
  labels:
    app: jade-accounts
spec:
  type: NodePort
  selector:
    app: jade-accounts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4203
      nodePort: 30008
      name: jade-accounts
