export default [
  {
    id: 11001,
    imageUrl: '/images/products/apple.jpg',
    imageAlt: 'Pink Lady Apple Minimum 4 Pack',
    title: 'Pink Lady Apple Minimum 4 Pack',
    formattedPrice: '$2.90',
    priceUnit: ' / 4pc',
    reviewCount: 34,
    rating: 4,
    onSale: true,
  },
  {
    id: 11002,
    imageUrl: '/images/products/capsicum-green.jpg',
    imageAlt: 'Green Pepper Each',
    title: 'Green Pepper Each',
    formattedPrice: '$0.30',
    priceUnit: ' / each',
    reviewCount: 20,
    rating: 5,
    onSale: false,
  },
  {
    id: 11003,
    imageUrl: '/images/products/kiwi-green.jpg',
    imageAlt: 'Chile Kiwi Green',
    title: 'Chile Kiwi Green',
    formattedPrice: '$1.75',
    priceUnit: ' / 3pc',
    reviewCount: 37,
    rating: 3,
    onSale: false,
  },
  {
    id: 11004,
    imageUrl: '/images/products/pomegranate.jpg',
    imageAlt: '5 day shell life Pomegranate',
    title: 'Pomegranate Seeds 80gm',
    formattedPrice: '$1.00',
    priceUnit: ' / 80g',
    reviewCount: 55,
    rating: 4,
    onSale: false,
  },
  {
    id: 11005,
    imageUrl: '/images/products/tomato.jpg',
    imageAlt: 'Large On The Vine Tomatoes 450G',
    title: 'Large On The Vine Tomatoes 450G',
    formattedPrice: '$1.25',
    priceUnit: ' / 450g',
    reviewCount: 32,
    rating: 4,
    onSale: false,
  },
];
