apiVersion: apps/v1
kind: Deployment
metadata:
  name: jade-graphql-gateway
  namespace: grocery-dev
  labels:
    app: jade-graphql-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jade-graphql-gateway
  template:
    metadata:
      labels:
        app: jade-graphql-gateway
    spec:
      containers:
        - name: jade-graphql-gateway
          image: harbor.instg.pscloudhub.com/iris/jade-graphql-gateway:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 60
          env:
            - name: CURRENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"
            - name: LOG_LEVEL
              value: debug
            - name: SERVICE_LIST
              valueFrom:
                configMapKeyRef:
                  name: graphql-gateway-configmap
                  key: SERVICE_LIST
