export default [
  {
    isToggleAble: true,
    isExpanded: true,
    label: 'Baby Care',
    data: [
      {
        isToggleAble: true,
        isExpanded: true,
        label: 'Child Cat11',
        data: [
          {
            isToggleAble: false,
            isExpanded: false,
            label: 'Child Cat111',
            data: [],
            id: '111',
            parentId: 11,
            link: '/c/11/111',
          },
          {
            isToggleAble: false,
            isExpanded: false,
            label: 'Child Cat111',
            data: [],
            id: '222',
            parentId: 11,
            link: '/c/11/222',
          },
        ],
        id: '11',
        parentId: 1,
      },
      {
        isToggleAble: false,
        isExpanded: false,
        label: 'Child Cat22',
        data: [],
        id: '22',
        parentId: 1,
        link: '/c/1/22',
      },
      {
        isToggleAble: false,
        isExpanded: false,
        label: 'Child Cat33',
        data: [],
        id: '33',
        parentId: 1,
        link: '/c/1/33',
      },
    ],
    id: '1',
  },
  {
    isToggleAble: true,
    isExpanded: false,
    label: 'Baby Care1',
    data: [
      {
        isToggleAble: false,
        isExpanded: false,
        label: 'Child Cat44',
        data: [],
        id: '44',
        parentId: 2,
        link: '/c/2/44',
      },
      {
        isToggleAble: false,
        isExpanded: false,
        label: 'Child Cat55',
        data: [],
        id: '55',
        parentId: 2,
        link: '/c/2/55',
      },
      {
        isToggleAble: false,
        isExpanded: false,
        label: 'Child Cat66',
        data: [],
        id: '66',
        parentId: 2,
        link: '/c/2/66',
      },
    ],
    id: '2',
  },
  {
    isToggleAble: true,
    isExpanded: true,
    label: 'Baby Care2',
    data: [
      {
        isToggleAble: false,
        isExpanded: false,
        label: 'Child Cat77',
        data: [],
        id: '77',
        parentId: 3,
        link: '/c/1/77',
      },
      {
        isToggleAble: false,
        isExpanded: false,
        label: 'Child Cat88',
        data: [],
        id: '88',
        parentId: 3,
        link: '/c/1/88',
      },
      {
        isToggleAble: false,
        isExpanded: false,
        label: 'Child Cat99',
        data: [],
        id: '99',
        parentId: 3,
        link: '/c/1/99',
      },
    ],
    id: '3',
  },
  {
    isToggleAble: false,
    isExpanded: false,
    label: 'Baby Care4',
    data: [],
    id: '4',
    link: '/c/4',
  },
  {
    isToggleAble: false,
    isExpanded: false,
    label: 'Baby Care5',
    data: [],
    id: '5',
    link: '/c/5',
  },
  {
    isToggleAble: false,
    isExpanded: false,
    label: 'Baby Care6',
    data: [],
    id: '6',
    link: '/c/6',
  },
];
